### ISSUE TITLE
Date error shows even if date is valid

### ISSUE THREAD

**Issue by mlonn** [mlonn/SPCw#10]
**Describe the bug**
when I fill the form, then click in the duration for the first activity and use the tab key to move through the date for the second activity to the power column, I get an "Error: Invalid date" even though the date is valid and I didnt change it

**To Reproduce**
I could not reproduce

**Expected behavior**
Error should not show if date is valid

**Comment by f1r2a** [comment]
Looks like it's to do with my language setting and having a date in the field(s) in dd/mm/yyyy format. If I enter a date directly using that format (the English (UK) setting) I get the same error.

**Comment by mlonn** [comment]
Removed the input field instead since date formatting is weird.
