### ISSUE TITLE
Calculations using Riegel exponents not matching input/output power units correctly

### ISSUE THREAD

**Issue by misterbates** [mlonn/SPCw#13]
**Describe the bug**
For the calculations "FTP/CP from prior race", "Race Target power using ... (all 3 calcs)"

When entering prior race results regardless of which output units are chosen, the result is always shown in units matching the input power units ... if the output units are then changed, the result is either divided by or multiplied by weight depending on the change made to output units.

**To Reproduce**
1. Enter race results as 320w, 0:21:00 with Riegel -0.08
2. Select Watts as output units and click calculate to see FTP/CP=298.55 W
3. Change output units to Watts/kg to see 4.03 W/kg
4. Leave Watts/kg chosen and click calculate again to see 298.55 W/kg
5. Change output units to Watts to see 22092.34 W

**Expected behavior**
The calculation can be made using Watts or Watts/kg as the input units, but the result (in same units as the input) needs to be adjusted based on the units of the output.

For example, entering prior race power in Watts should give an FTP/CP in Watts, which can be shown as-is if the output units are Watts, or divided by weight if output in W/kg.

Conversely, entering prior race power in Watts/kg should give an FTP/CP in Watts/kg, which can be shown as-is if the output units are Watts/kg, or multiplied by weight if output in W.

**Screenshots**
Attached to issue in GitHub. Shows the result of entering Watts, selecting Watts/kg as output units, clicking [calculate], then changing output units to Watts.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by misterbates** [comment]
![image](https://user-images.githubusercontent.com/64629344/84367565-5373d680-abcc-11ea-9849-07facba6f9b1.png)

**Comment by mlonn** [comment]
@misterbates Great and detailed issue report. Will look in to it.
